name: SanITyWorx
favicon: null
layout_spectrum: 0.49489
typography_spectrum: 0.87548
title: SanITyWorx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c6c6c6'
    - '#000000'
    - '#8d8d8d'
    - '#365873'
  brandStrength: 0.3125
  lightness: 0.43681591912172735
  saturation: 0.125
  rhythmicContrast: 0.8799920023884624
purpose: []
