name: SanITyWorx
favicon: null
layout_spectrum: 0.49489
typography_spectrum: 0.8298600723501295
title: SanITyWorx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.43681591912172735
  saturation: 0.9154452276416123
  rhythmicContrast: 0.8799920023884624
purpose: []
